### ISSUE TITLE
strictNullCheck not working

### ISSUE THREAD

**Issue by michaelkastner** [FlareMind/typescript-observable#1]
in your example you are using
` { parent: null ....}`
if I use this, i get:
Types of property 'parent' are incompatible.
    Type 'null' is not assignable to type 'IObservableEvent'

I worked around that by using this interface in the .d.ts file:
```
export interface IObservableEvent {
    parent: IObservableEvent | null;
    name: string;
}

```

**Comment by afsa** [comment]
I had the impression that fields always can be set to null. However, I will implement your suggested change.
